name: SQLite Database Setup and Query

on: [push]

jobs:
  build-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run SQLite script
        run: python scripts/setup_and_query.py

      - name: Upload SQLite DB artifact
        uses: actions/upload-artifact@v4
        with:
          name: sqlite-database
          path: tycl.db